### ISSUE TITLE
Run tests on GitHub actions

### ISSUE THREAD

**Issue by dreynolds** [jmons/riffdog#16]
Since I added a couple of tests, would be nice to actually run them presumably on GH actions if we can.

Also, I used pytest because it's much nicer than nose (is nose even still used nowadays)?

**Comment by dreynolds** [comment]
@Jamian @jmons any ideas on what sort of test running scheme we want? On every push?

**Comment by jmons** [comment]
I think every push - I think having a culture of fewer, working commits rather then WIP is probably appropriate for this. Wasn't sure about the pytest/nose thing because somewhere (and I want to say pypi?) guidelines where like 'you should use nose'. 

I'll look at adding Tox which I think will help with the setup.py part and actually tests the setup.py rather then the code inside (incase theres any exclude type thing).
